# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_linear_regression_model
display_name: Train a Linear Regression Model
version: 1
type: command
inputs:
  training_data: 
    type: uri_folder
  regularization_rate: 
    type: number
    default: 0.01
outputs:
  model_output:
    type: uri_folder
code: ./src
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python train-linear-regression.py 
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.regularization_rate}}
  --model_output ${{outputs.model_output}}
# </component>
